version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio-for-fatsy
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
    volumes:
      - ./minio/data:/data
    entrypoint: minio server /data --console-address ":9090"