app:
  title: My demo API server

server:
  host: "0.0.0.0"
  port: 3000
  logger:
    level: warn
  body_limit: 50mb
  https:
    key: "server.key"
    cert: "server.pem"
  auth:
    secret: SuperSecret

temmplating:
  engine: handlebars
  base: "templates"