name: Conventional Commits

on:
  push:

  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt install jq

      - name: set status to pending
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
           -d '{"state":"pending","description":"The PR message check is failed!","context":"ci-pr-check"}'

      - name: Check PR commit message
        run: |
               echo "PR SHA: $GITHUB_SHA"
               #          commit_message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
               #          commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)
               curl -L \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
               https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA | jq 
               echo "Commit Message: $commit_message"
          
          #          if ! [[ $commit_message =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\s.+ ]]; then
          #            echo "::error::The commit message does not follow the conventional commit format."
          #
               curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
               -d '{"state":"failure","description":"The PR message check is failed!","context":"ci-pr-check"}'
      #
      #            exit 1
      #          fi

      - name: Check branch for merging to 'main'
        run: |
          if [[ ${{ github.ref }} != 'refs/heads/develop' ]]; then
            echo "::error::Only 'develop' branch can be merged into 'main'."
            exit 1
          fi

      - name: Check branch for merging to 'develop'
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::error::Only branches other than 'main' can be merged into 'develop'."
            exit 1
          fi

      - name: Update PR status check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            
            await octokit.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'PR-Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'PR Commit Message Check',
                summary: 'The commit message follows the conventional commit format.',
              },
            });