name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt install jq

      - name: set status to pending
        run: |
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
           -d '{"state":"pending","description":"The PR message check is failed!","context":"ci-pr-check"}'

      - name: Check PR title check
        run: |
          echo "PR SHA: $GITHUB_SHA"
          echo "Title: ${{github.event.pull_request.title}}"
          
          REGEX="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([[:alnum:]._-]+\))?(!)?: ([[:alnum:]])+([[:space:][:print:]]*)"

          if ! [[ "${{github.event.pull_request.title}}" =~ $REGEX ]]; then
            echo "::error::The PR title does not follow the conventional commit format."

            curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
               -d '{"state":"failure","description":"The PR title check is failed!","context":"ci-pr-check"}'

            exit 1
          fi

      - name: Check branch for merging to 'main'
        run: |
          if [[ ${{ github.ref }} != 'refs/heads/develop' ]]; then
            echo "::error::Only 'develop' branch can be merged into 'main'."
            exit 1
          fi

      - name: Check branch for merging to 'develop'
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::error::Only branches other than 'main' can be merged into 'develop'."
            exit 1
          fi
      - name: Report status
        if: always()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
          -d '{"state":"success","description":"The PR title check is finished!","context":"ci-pr-check"}'