name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt install jq

      - name: Check PR title check
        run: |
          echo "PR SHA: $GITHUB_SHA"
          echo "Title: ${{github.event.pull_request.title}}"
          
          REGEX="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([[:alnum:]._-]+\))?(!)?: ([[:alnum:]])+([[:space:][:print:]]*)"
          
          if ! [[ "${{github.event.pull_request.title}}" =~ $REGEX ]]; then
            echo "::error::The PR title does not follow the conventional commit format."
            exit 1
          fi

      - name: Check branch for merging to 'main'
        run: |
          if [[ ${{ github.ref }} != 'refs/heads/develop' ]]; then
            echo "::error::Only 'develop' branch can be merged into 'main'."
          
            exit 1
          fi

      - name: Check branch for merging to 'develop'
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::error::Only branches other than 'main' can be merged into 'develop'."
          
            exit 1
          fi
